### ISSUE TITLE
error on context.add_callback when using grpc-web

### ISSUE THREAD

**Issue by parlance-zz** [hafriedlander/stable-diffusion-grpcserver#13]
I tried using imperator's PS plugin with my grpc fork and was getting this error, but my generate.py isn't modified. Can you confirm if this is just me? Everything works fine if I comment out the line that adds the stop event callback.

Traceback (most recent call last):
  File "D:\g-diffuser-bot\extensions\stable-diffusion-grpcserver\sdgrpcserver\services\generate.py", line 167, in Generate
    context.add_callback(lambda: stop_event.set())
TypeError: ServicerContext.add_callback() takes 1 positional argument but 2 were given
WSGI application error
Traceback (most recent call last):
  File "C:\Users\parla\miniconda3\envs\g_diffuser\lib\site-packages\twisted\python\threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "C:\Users\parla\miniconda3\envs\g_diffuser\lib\site-packages\twisted\python\context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\parla\miniconda3\envs\g_diffuser\lib\site-packages\twisted\python\context.py", line 84, in callWithContext
    self.contexts.pop()
  File "C:\Users\parla\miniconda3\envs\g_diffuser\lib\site-packages\twisted\web\wsgi.py", line 530, in run
    self.started = True
--- <exception caught here> ---
  File "C:\Users\parla\miniconda3\envs\g_diffuser\lib\site-packages\twisted\web\wsgi.py", line 500, in run
    for elem in appIterator:
  File "D:\g-diffuser-bot\extensions\stable-diffusion-grpcserver\sdgrpcserver\sonora\wsgi.py", line 123, in _do_grpc_request
    yield from self._do_streaming_response(
builtins.RuntimeError: generator raised StopIteration

**Comment by hafriedlander** [comment]
This should have been fixed by this patch:
https://github.com/hafriedlander/stable-diffusion-grpcserver/commit/98639b4831cad628c6e5e731cecf0e141489ee44
